#ifndef __VWCMANTILEECHDRVIOCTL_HEADER__
#define __VWCMANTILEECHDRVIOCTL_HEADER__


/**
 *	driver name
 */
#define DEVIE_NAMEA		"VwCmAntiLeechDrv"
#define DEVIE_NAMEW		L"VwCmAntiLeechDrv"
#define NT_DEVICE_NAME		L"\\Device\\VwCmAntiLeechDrv"
#define DOS_DEVICE_NAME		L"\\DosDevices\\VwCmAntiLeechDrv"
#define DRIVER_FILEA		"VwCmAntiLeechDrv.sys"
#define DRIVER_FILEW		L"VwCmAntiLeechDrv.sys"
#define DRIVER_DESCA		"VirtualWall Universal Anti-Leech Driver"
#define DRIVER_DESCW		L"VirtualWall Universal Anti-Leech Driver"

//
//	Define the various device type values.  Note that values used by Microsoft
//	Corporation are in the range 0-32767, and 32768-65535 are reserved for use
//	by customers.
//
//	Device type
#define VWCMANTILEECHDRV_FILE_DEVICE	0x00697919
#define VWCMANTILEECHDRV_IOCTL_INDEX	0x830


/**
 *	IOCTLs
 */
#define VWCMANTILEECHDRV_IOCTL_START		CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x1, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWCMANTILEECHDRV_IOCTL_STOP		CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x2, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWCMANTILEECHDRV_IOCTL_LOADCFG		CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x3, METHOD_BUFFERED, FILE_ANY_ACCESS )

#define VWCMANTILEECHDRV_IOCTL_ISSTART		CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x10, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWCMANTILEECHDRV_IOCTL_ISCORERUN	CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x11, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWCMANTILEECHDRV_IOCTL_RTSP_ISCORERUN	CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x12, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWCMANTILEECHDRV_IOCTL_RTSP_BLOCKCOUNT	CTL_CODE( VWCMANTILEECHDRV_FILE_DEVICE, VWCMANTILEECHDRV_IOCTL_INDEX+0x13, METHOD_BUFFERED, FILE_ANY_ACCESS )







#endif	// __VWCMANTILEECHDRVIOCTL_HEADER__

