#ifndef __VWPANDMNEWDRVIOCTL_HEADER__
#define __VWPANDMNEWDRVIOCTL_HEADER__


/**
 *	driver name
 */
#define DEVIE_NAMEA		"VwPanDmNewDrv"
#define DEVIE_NAMEW		L"VwPanDmNewDrv"
#define NT_DEVICE_NAME		L"\\Device\\VwPanDmNewDrv"
#define DOS_DEVICE_NAME		L"\\DosDevices\\VwPanDmNewDrv"
#define DRIVER_FILEA		"VwPanDmNewDrv.sys"
#define DRIVER_FILEW		L"VwPanDmNewDrv.sys"
#define DRIVER_DESCA		"VirtualWall PanDomain Driver"
#define DRIVER_DESCW		L"VirtualWall PanDomain Driver"

//
//	Define the various device type values.  Note that values used by Microsoft
//	Corporation are in the range 0-32767, and 32768-65535 are reserved for use
//	by customers.
//
//	Device type
#define VWPANDMNEWDRV_FILE_DEVICE	0x00697909
#define VWPANDMNEWDRV_IOCTL_INDEX	0x830


/**
 *	IOCTLs
 */
#define VWPANDMNEWDRV_IOCTL_START	CTL_CODE( VWPANDMNEWDRV_FILE_DEVICE, VWPANDMNEWDRV_IOCTL_INDEX+0x1, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWPANDMNEWDRV_IOCTL_STOP	CTL_CODE( VWPANDMNEWDRV_FILE_DEVICE, VWPANDMNEWDRV_IOCTL_INDEX+0x2, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWPANDMNEWDRV_IOCTL_ISSTART	CTL_CODE( VWPANDMNEWDRV_FILE_DEVICE, VWPANDMNEWDRV_IOCTL_INDEX+0x3, METHOD_BUFFERED, FILE_ANY_ACCESS )
#define VWPANDMNEWDRV_IOCTL_LOADCFG	CTL_CODE( VWPANDMNEWDRV_FILE_DEVICE, VWPANDMNEWDRV_IOCTL_INDEX+0x4, METHOD_BUFFERED, FILE_ANY_ACCESS )





#endif	// __VWPANDMNEWDRVIOCTL_HEADER__

