//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by VwFirewallCfg.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_VWFIREWALLCFG_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDB_BITMAP_TITLE                129
#define IDC_CURSOR_HAND                 138
#define IDR_MENU_SYSTRAY                139
#define IDD_TAB_BLOCK                   140
#define IDD_TAB_EXCEPTION               141
#define IDD_TAB_GENERAL                 143
#define IDI_ICON_O                      144
#define IDI_ICON_X                      145
#define IDB_BITMAP_STATUS_X             147
#define IDB_BITMAP_STATUS_O             148
#define IDB_BITMAP_SHIELD_GREEN         149
#define IDB_BITMAP_SHIELD_RED           150
#define IDI_ICON_SHIELD_GREEN           151
#define IDI_ICON_SHIELD_RED             152
#define IDI_ICON_SYSTRAY_STOPPED        154
#define IDI_ICON_SYSTRAY_RUN            155
#define IDI_ICON_SYSTRAY_RUNNING        156
#define IDI_ICON_SHIELD_YELLOW          157
#define IDB_BITMAP_SHIELD_YELLOW        158
#define IDB_BITMAP_STATUS_WAIT          159
#define IDB_BITMAP_IMGLIST_TREE         162
#define IDD_TAB_ABOUT                   163
#define IDD_TAB_UPDATE                  165
#define IDD_TAB_LICENSE                 166
#define IDD_TAB_SETTING                 167
#define IDD_TAB_FILTER                  168
#define IDB_BITMAP_BUTTON_APPLY         169
#define IDB_BITMAP_BUTTON_RESTORE       170
#define IDD_DLG_ENTERKEY                171
#define IDB_BITMAP_BUTTON_LICENSE_KEY   172
#define IDB_BITMAP_BUTTON_LICENSE_CHECK 173
#define IDD_DLG_BUILDDICT               174
#define IDD_TAB_ANTISQL                 175
#define IDD_TAB_DOMAIN                  176
#define IDD_DLG_DMADD                   177
#define IDD_DIALOG_EXPIRE               179
#define IDD_DLG_IMPORT                  180
#define IDD_TAB_RDP                     181
#define IDD_DLG_CLIENTADD               182
#define IDI_ICON_STATUS_RDP_X           183
#define IDI_ICON_STATUS_DOMAIN_OK       184
#define IDI_ICON_STATUS_DOMAIN_X        185
#define IDI_ICON_STATUS_RDP_OK          186
#define IDI_ICON_STATUS_X               187
#define IDI_ICON_STATUS_OK              188
#define IDD_DLG_SETRDPPORT              189
#define IDB_BITMAP_SPLASH               191
#define IDD_DLG_SPLASH                  192
#define IDD_TAB_FILE                    193
#define IDR_MENU_ADD_EP                 193
#define IDD_DLG_PROTECTEDDIR_ADD        194
#define IDI_ICON_STATUS_FILE_OK         194
#define IDI_ICON_STATUS_FILE_X          195
#define IDD_TAB_SECURITYCFG             196
#define IDD_TAB_SECURITYCFG_ACLS_FILE   197
#define IDI_ICON_ALERT                  199
#define IDI_ICON_OK                     200
#define IDI_ICON_UNKNOWN                201
#define IDI_ICON_WAIT_S                 202
#define IDI_ICON_ARROW_R                204
#define IDD_TAB_SECURITYCFG_ACLS_FOLDER 205
#define IDR_MENU_SVC_LIST               206
#define IDD_DLG_DETAIL                  207
#define IDR_MENU_ACLS_LIST              207
#define IDI_ICON_LOADING1               208
#define IDD_TAB_SECURITYCFG_ACLS_ANTIVIRUS 208
#define IDI_ICON_LOADING2               209
#define IDD_TAB_SECURITYCFG_SERVICE     209
#define IDI_ICON_LOADING3               210
#define IDI_ICON_LOADING4               211
#define IDI_ICON_LOADING5               212
#define IDI_ICON_LOADING6               213
#define IDD_DLG_SERVICE                 214
#define IDD_TAB_SECURITYCFG_OBJECT      215
#define IDD_DLG_RECOVER_REG             216
#define IDD_DLG_RECOVER_SECURITY        217
#define IDI_ICON_INFO                   218
#define IDI_ICON_OKB                    219
#define IDB_BITMAP_BUTTON_DETECT        220
#define IDB_BITMAP_BUTTON_FIX           221
#define IDC_BUTTON_RESTORE              1010
#define IDC_STATIC_DESAFE               1012
#define IDC_EDIT_EXCEPTION_HOSTS        1013
#define IDC_EDIT_OUT_REP_WORDS          1014
#define IDC_BUTTON_SAVE                 1018
#define IDC_STATIC_HINT_IN              1019
#define IDC_BUTTON_MODRDPPORT           1019
#define IDC_STATIC_SET_IN_ALERT         1020
#define IDC_STATIC_HINT_OUT             1021
#define IDC_STATIC_HINT                 1021
#define IDC_CHECK_START                 1022
#define IDC_STATIC_DOWNLOAD_DATA        1022
#define IDC_CHECK_LOG                   1024
#define IDC_STATIC_HINT_DOMAIN          1025
#define IDC_EDIT_IN_BLOCK_WORDS         1026
#define IDC_STATIC_ABOUT_MORE           1028
#define IDC_STATIC_VIEW_LOGS            1029
#define IDC_TREE_MENU                   1029
#define IDC_STATIC_CAP                  1030
#define IDC_STATIC_LINK_VW              1031
#define IDC_STATIC_CURRVER              1032
#define IDC_STATIC_DOWNLOAD             1033
#define IDC_RICHEDIT_INFO               1034
#define IDC_STATIC_HOWTOBUY             1035
#define IDC_BUTTON_ENTER_KEY            1036
#define IDC_BUTTON_ONLINE_CHECK         1037
#define IDC_STATIC_STATUS               1038
#define IDC_STATIC_FIREWALLSTATUS       1039
#define IDC_EDIT_FILTERFILEPATH         1040
#define IDC_STATIC_STATUS_DOMAIN        1040
#define IDC_BUTTON_REFRESH              1041
#define IDC_BUTTON_STOP                 1041
#define IDC_STATIC_STATUS_DOMAIN_TXT    1041
#define IDC_BUTTON_INSTALL_FILTER       1042
#define IDC_BUTTON_START                1042
#define IDC_STATIC_STATUS_RDP           1042
#define IDC_CHECK_BLOCKPOST             1043
#define IDC_STATIC_STATUS_RDP_TXT       1043
#define IDC_STATIC_STATUS_FILE          1044
#define IDC_CHECK_BLOCKPOSTSIZE         1045
#define IDC_STATIC_STATUS_FILE_TXT      1045
#define IDC_COMBO_BLOCKPOSTSIZECFG      1046
#define IDC_STATIC_BLOCKUPLOADFILESIZE_HINT 1047
#define IDC_COMBO_REGIP                 1049
#define IDC_EDIT_REGKEY                 1050
#define IDC_BUTTON_COPY                 1052
#define IDC_STATIC_LINK_DISCUSS         1053
#define IDC_STATIC_LINK_AD              1054
#define IDC_STATIC_SPLIT1               1055
#define IDC_BUTTON_CHECKFORUPDATE       1056
#define IDC_EDIT_IN_ANTISQL_WORDS       1057
#define IDC_STATIC_HINTBTM              1058
#define IDC_BUTTON_ADD                  1059
#define IDC_BUTTON_DEL                  1060
#define IDC_BUTTON_MOD                  1061
#define IDC_LIST_DOMAIN                 1062
#define IDC_BUTTON_ADD_EP               1062
#define IDC_EDIT_PANDOMAIN              1063
#define IDC_BUTTON_TEST                 1063
#define IDC_BUTTON_IMP                  1063
#define IDC_BUTTON_DEL_EP               1063
#define IDC_EDIT_TODOMAIN               1064
#define IDC_EDIT_EXCEPT_SUBDOMAIN       1065
#define IDC_STATIC_REMARK1              1066
#define IDC_CHECK_USE                   1067
#define IDC_STATIC_APPNAME              1068
#define IDC_CHECK_MAPEDDIRDM            1068
#define IDC_STATIC_HOWTO_GET_SUBDOMAIN  1069
#define IDC_STATIC_INFO                 1070
#define IDC_STATIC_HOWTORENEW           1071
#define IDC_STATIC_LINK_HELPDOC         1072
#define IDC_STATIC_SPLIT2               1073
#define IDC_BUTTON_IMPORT               1075
#define IDC_CHECK_PDOMAIN               1076
#define IDC_EDIT_CLIENTNAME             1077
#define IDC_LIST_RDP                    1078
#define IDC_EDIT_ECPEXT                 1078
#define IDC_CHECK_STARTPRDP             1079
#define IDC_BUTTON_STATUS               1080
#define IDC_BUTTON_DOMAIN               1081
#define IDC_STATIC_CTLLINK_FIREWALL     1081
#define IDC_BUTTON_RDP                  1082
#define IDC_STATIC_CTLLINK_DOMAIN       1082
#define IDC_EDIT_ORG_PORT               1082
#define IDC_BUTTON_LICENSE              1083
#define IDC_STATIC_CTLLINK_RDP          1083
#define IDC_EDIT_NEW_PORT               1083
#define IDC_BUTTON_UPDATE               1084
#define IDC_CHECK_ADDTO_FW_EXCEPTION    1084
#define IDC_STATIC_CTLLINK_FILE         1084
#define IDC_STATIC_PDOMAIN_BLOCKCOUNT   1085
#define IDC_BUTTON_SECURITYCFG          1085
#define IDC_STATIC_PRDP_BLOCKCOUNT      1086
#define IDC_STATIC_TITIMAGE             1087
#define IDC_STATIC_PFILE_BLOCKCOUNT     1087
#define IDC_STATIC_IMAGE                1088
#define IDC_STATIC_CTLLINK_FILE_SET     1088
#define IDC_LIST_PROTECTEDDIR           1089
#define IDC_STATIC_CTLLINK_DOMAIN_SET   1089
#define IDC_LIST_EXCEPTEDPROCESS        1090
#define IDC_CHECK_TREE                  1090
#define IDC_STATIC_CTLLINK_RDP_SET      1090
#define IDC_BUTTON_BROWSERDIR           1091
#define IDC_STATIC_CTLLINK_FILE_SP      1091
#define IDC_EDIT_DIR                    1092
#define IDC_STATIC_CTLLINK_DOMAIN_SP    1092
#define IDC_BUTTON_ADD_DIR              1093
#define IDC_STATIC_CTLLINK_RDP_SP       1093
#define IDC_BUTTON_DEL_DIR              1094
#define IDC_BUTTON_MOD_DIR              1095
#define IDC_RADIO_ACLS_FILE             1097
#define IDC_LIST_GROUP                  1098
#define IDC_RADIO_ACLS_ANTIVIRUS        1098
#define IDC_BUTTON_DETECT               1099
#define IDC_RADIO_SERVICE               1099
#define IDC_BUTTON_FIX                  1100
#define IDC_RADIO_OBJECT                1100
#define IDC_PROGRESS_BAR                1101
#define IDC_RADIO_ACLS_FOLDER           1101
#define IDC_BUTTON_RECOVER              1102
#define IDC_LIST_DETAIL                 1103
#define IDC_LIST_FILE                   1105
#define IDC_STATIC_INFOICON             1107
#define IDS_APP_NAME                    2000
#define IDS_APP_STARTUP                 2001
#define IDS_APP_CAPTION                 2002
#define IDS_LANGCODE                    2100
#define IDS_LANGNAME                    2101
#define IDS_FONTNAME                    2102
#define IDS_MSG_CAPTION_WARNING         2203
#define IDS_MSG_CAPTION_PROMPT          2204
#define IDS_MSG_CAPTION_ERR             2205
#define IDS_MSG_CAPTION_NOTICE          2206
#define IDS_MSG_CAPTION_RESULT          2207
#define IDS_MSG_CAPTION_CONGLT          2208
#define IDS_MSG_CAPTION_CONFIRM         2209
#define IDS_ALREADYRUN                  2300
#define IDS_VERSION                     2301
#define IDS_WORKINGDIR_ERROR_CAP        2302
#define IDS_WORKINGDIR_ERROR_MSG        2303
#define IDS_STRING_LICENSE_OK           2304
#define IDS_STRING_LICENSE_EVALUATE     2305
#define IDS_STRING_LICENSE_CONNSRV      2306
#define IDS_STRING_LICENSE_FAILEDCONN   2307
#define IDS_STRING_REGCONTENTS          2308
#define IDS_STRING_REGNOLMT             2309
#define IDS_STRING_BTN_FINS             2310
#define IDS_STRING_BTN_FUINS            2311
#define IDS_STRING_ERR_PANDM            2312
#define IDS_DLGCLIENTADD_ERR_PCNAME     2313
#define IDS_DLGDMADD_ERR_DOMAIN         2314
#define IDS_LISTN_DOMAIN                2315
#define IDS_LISTN_STATUS                2316
#define IDS_LISTN_COMPUTERNAME          2317
#define IDS_LISTN_IMPORTRESULT          2318
#define IDS_LISTS_ALLOW                 2319
#define IDS_LISTS_IMPORTSUCC            2320
#define IDS_LISTS_DOMAINEXIST           2321
#define IDS_DLGSETRDPPORT_MODIFY_SUCC   2322
#define IDS_DLGSETRDPPORT_ERR_ADDPORT_EXP1 2323
#define IDS_DLGSETRDPPORT_ERR_ADDPORT_EXP2 2324
#define IDS_DLGSETRDPPORT_ERR_ADDPORT_EXP3 2325
#define IDS_DLGENTERKEY_ERR_UPDATE      2326
#define IDS_LISTS_DENY                  2327
#define IDS_TABDOMAIN_ERR_TOOMUCH_DOMAINS 2328
#define IDS_TABDOMAIN_ERR_BIGDATA       2329
#define IDS_TABDOMAIN_ERR_DMEXIST1      2330
#define IDS_TABDOMAIN_ERR_DMEXIST2      2331
#define IDS_TABDOMAIN_ERR_OP1           2332
#define IDS_TABDOMAIN_ERR_SAVESUCC      2333
#define IDS_TABRDP_ERR_TOOMUCH_DOMAINS  2334
#define IDS_TABRDP_ERR_PCNEXIST1        2335
#define IDS_TABRDP_ERR_PCNEXIST2        2336
#define IDS_TABRDP_ERR_OP1              2337
#define IDS_TABRDP_ERR_SAVESUCC         2338
#define IDS_TABRDP_ERR_BIGDATA          2339
#define IDS_TABSETTING_ERR_INS1         2340
#define IDS_TABSETTING_ALERT_RDP1       2341
#define IDS_TABSETTING_ERR_RDP1         2342
#define IDS_TABSETTING_ERR_START        2343
#define IDS_TABSETTING_ERR_STOP         2344
#define IDS_TABSETTING_STR_STOPFW       2345
#define IDS_TABSETTING_STR_STARTFW      2346
#define IDS_TABSETTING_STR_RUNNING      2347
#define IDS_TABSETTING_STR_STOPPED      2348
#define IDS_TABSETTING_STR_INFO1        2349
#define IDS_TABSETTING_STR_INFO2        2350
#define IDS_TABSETTING_STR_INFO3        2351
#define IDS_TABSETTING_STR_DM_RUNNING   2352
#define IDS_TABSETTING_STR_DM_STOPPED   2353
#define IDS_TABSETTING_STR_STOP_PROTECT 2354
#define IDS_TABSETTING_STR_START_PROTECT 2355
#define IDS_TABSETTING_STR_RDP_RUNNING  2356
#define IDS_TABSETTING_STR_RDP_STOPPED  2357
#define IDS_TABRDP_ERR_EMPTYHINT        2358
#define IDS_TABSETTING_STR_FILE_RUNNING 2359
#define IDS_TABSETTING_STR_FILE_STOPPED 2360
#define IDM_MENU_SYSTRAY_EXIT           32771
#define IDM_MENU_SYSTRAY_OPEN           32772
#define IDM_MENU_SYSTRAY_DEHOMEPAGE     32773
#define IDM_MENU_SYSTRAY_OPENWORKINGDIR 32774
#define IDM_MENU_SYSTRAY_STARTAUTO      32775
#define IDM_MENU_SYSTRAY_OPENHELPDOC    32776
#define IDM_MENU_LIST_DETAIL            32777
#define IDM_MENU_LIST_SVC_START         32779
#define IDM_MENU_LIST_SVC_STOP          32780

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        222
#define _APS_NEXT_COMMAND_VALUE         32781
#define _APS_NEXT_CONTROL_VALUE         1108
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
